name: Deployment

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.6" # The Go version to download (if necessary) and use.
      - name: Run Build
        run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: build/*
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

